### ISSUE TITLE
Proxy multiple containers does not seem to work

### ISSUE THREAD

**Issue by g000444555** [dperson/nginx#17]
Hi, thank you for maintaining this image.

I have the following problem when trying to configure reverse proxy to multiple containers with

`command: -w "http://transmission:9091;/transmission" -w "http://couchpotato:5050;/couchpotato"`

I can access the following URL normally

https://localhost:443/transmission

However, when I try to access https://localhost:443/couchpotato the following happen

- The 'Welcome to nginx!' page appears
- The URL is rewritten to https://localhost:443/#couchpotato
- I get the following logs
```
docker-compose logs -f nginx-reverse-proxy
Attaching to nginx-reverse-proxy
nginx-reverse-proxy    | Generating a 2048 bit RSA private key
nginx-reverse-proxy    | ................+++
nginx-reverse-proxy    | .............................................+++
nginx-reverse-proxy    | unable to write 'random state'
nginx-reverse-proxy    | writing new private key to '/etc/nginx/ssl/privkey.pem'
nginx-reverse-proxy    | -----
nginx-reverse-proxy    | 172.18.0.1 - ant [08/Mar/2018:19:52:59 +0000] "GET / HTTP/2.0" 200 384 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "-" 0.000 -
ginx-reverse-proxy    | 172.18.0.1 - ant [08/Mar/2018:19:53:52 +0000] "GET / HTTP/2.0" 200 384 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "-" 0.000 -
```

I have verified http://couchpotato:5050 is responding from within the container.

Could you please advise or fix the issue?

My docker-compose.yml is as follows:

```
version: '3.4'

services:
  openvpn-client:
    image: dperson/openvpn-client
    container_name: openvpn-client
    cap_add:
      - net_admin
    environment:
      TZ: 'GMT/UTC'
    read_only: true
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    networks:
      - default
    volumes:
      - /dev/net:/dev/net:z

  transmission:
    image: dperson/transmission
    depends_on:
      - openvpn-client
    container_name: transmission
    network_mode: "service:openvpn-client"
    environment:
      TZ: 'GMT/UTC'
    restart: unless-stopped
    stdin_open: true
    tty: true

  couchpotato:
    image: linuxserver/couchpotato
    depends_on:
      - openvpn-client
    container_name: couchpotato
    restart: unless-stopped
    network_mode: "service:openvpn-client"

  nginx-reverse-proxy:
    image: dperson/nginx
    container_name: nginx-reverse-proxy
    depends_on:
      - transmission
      - couchpotato
    environment:
      TZ: 'UTC'
    links:
      - openvpn-client:transmission
      - openvpn-client:couchpotato
    networks:
      - default
    ports:
      - "443:443"
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: -w "http://transmission:9091;/transmission" -w "http://couchpotato:5050;/couchpotato"

networks:
  default:
```

The resulting /etc/nginx/conf.d/default.conf is

```
# You may add here your
# server {
#    ...
# }
# statements for each of your virtual hosts to this file

##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# http://wiki.nginx.org/Pitfalls
# http://wiki.nginx.org/QuickStart
# http://wiki.nginx.org/Configuration
#
# Generally, you will want to move this file somewhere, and start with a clean
# file but keep this around for reference. Or just disable in sites-enabled.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

proxy_cache_path /var/cache/nginx/cache levels=1:2 keys_zone=mmcache:10m
            loader_threshold=300 loader_files=200 max_size=50m;


# HTTPS server
#
server {
    listen      443 ssl http2 default_server;
    listen      [::]:443 ssl http2 default_server;
    root        /srv/www;

    ssl_certificate      /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key  /etc/nginx/ssl/privkey.pem;

    # Make site accessible from http://localhost/
    server_name localhost;

    #charset koi8-r;
    #access_log  /var/log/nginx/log/host.access.log  main;
    error_log stderr;
    proxy_cache mmcache;

    location / {
        index  index.html index.htm;

        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files $uri $uri/ =404;
    }

    location /couchpotato {
        proxy_pass       http://couchpotato:5050;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        # Mitigate httpoxy attack (see README for details)
        proxy_set_header Proxy "";



        ## Required for websockets
        proxy_http_version 1.1;
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_read_timeout 600s;

        ## Optional: Do not log, get it at the destination
        access_log off;
    }

    location /transmission {
        proxy_pass       http://transmission:9091;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        # Mitigate httpoxy attack (see README for details)
        proxy_set_header Proxy "";



        ## Required for websockets
        proxy_http_version 1.1;
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_read_timeout 600s;

        ## Optional: Do not log, get it at the destination
        access_log off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    ## Handle the GFC (Great Firewal of China) breaking DNS for BT to random IPs
    location /announc {
        access_log off;
        error_log off;
        default_type text/plain;
        return 410 "d14:failure reason13:not a tracker8:retry in5:nevere";
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root html;
    #    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    #    # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
    #
    #    # With php5-cgi alone:
    #    fastcgi_pass 127.0.0.1:9000;
    #    # With php5-fpm:
    #    fastcgi_pass unix:/run/php5-fpm.sock;
    #    fastcgi_index index.php;
    #    fastcgi_param SCRIPT_FILENAME /scripts$fastcgi_script_name;
    #    include fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny all;
    #}

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}


server {
    listen 80;
    listen [::]:80;
    root   /srv/www;

    # Make site accessible from http://localhost/
    server_name localhost;

    #charset koi8-r;
    #access_log  /var/log/nginx/log/host.access.log  main;
    error_log stderr notice;
    proxy_cache mmcache;

    location / {
        index  index.html index.htm;

        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files $uri $uri/ =404;
    }

    location /couchpotato {
        proxy_pass       http://couchpotato:5050;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        # Mitigate httpoxy attack (see README for details)
        proxy_set_header Proxy "";



        ## Required for websockets
        proxy_http_version 1.1;
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_read_timeout 600s;

        ## Optional: Do not log, get it at the destination
        access_log off;
    }

    location /transmission {
        proxy_pass       http://transmission:9091;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        # Mitigate httpoxy attack (see README for details)
        proxy_set_header Proxy "";



        ## Required for websockets
        proxy_http_version 1.1;
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_read_timeout 600s;

        ## Optional: Do not log, get it at the destination
        access_log off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    ## Handle the GFC (Great Firewal of China) breaking DNS for BT to random IPs
    location /announc {
        access_log off;
        error_log off;
        default_type text/plain;
        return 410 "d14:failure reason13:not a tracker8:retry in5:nevere";
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}


# another virtual host using mix of IP-, name-, and port-based configuration
#
#server {
#    listen 8000;
#    listen somename:8080;
#    server_name somename alias another.alias;
#    root html;
#    index index.html index.htm;
#
#    location / {
#        try_files $uri $uri/ =404;
#    }
#}
```
